Lesson 4
========================================================

*** 
Load diamond dataset
```{r load diamonds}
library(ggplot2)
data(diamonds)
dim(diamonds)
str(diamonds)
is.ordered(diamonds$color)
levels(diamonds$color)
```
*** 
```{r price histogram}
ggplot(data = diamonds, aes(x = price)) + 
  geom_histogram(color = 'red', fill = 'yellow')

```

*** 
```{r}
summary(diamonds$price)
```

*** 
```{r}
#Diamonds cost less $500 
length(diamonds[diamonds$price < 500,]$price)
#Diamonds cost less $250
dim(subset(x = diamonds, price < 250))
#Diamonds cost more than or equal to 15000 
length(subset(diamonds, price >= 15000)$price)
```

*** 
```{r, warning=FALSE}
# Explore the largest peak in the
# price histogram you created earlier.

# Try limiting the x-axis, altering the bin width,
# and setting different breaks on the x-axis.

# There won’t be a solution video for this
# question so go to the discussions to
# share your thoughts and discover
# what other people find.

# You can save images by using the ggsave() command.
# ggsave() will save the last plot created.
# For example...
#                  qplot(x = price, data = diamonds)
#                  ggsave('priceHistogram.png')

# ggsave currently recognises the extensions eps/ps, tex (pictex),
# pdf, jpeg, tiff, png, bmp, svg and wmf (windows only).

# Submit your final code when you are ready.

ggplot(data = diamonds, aes(x = price)) + 
  geom_histogram(binwidth = 250, color = 'black', fill = 'light green') + 
  scale_x_continuous(limits = c(250, 5000), breaks = seq(0, 5000, 250)) + 
  labs(x = 'diamond prices in dollars', title = "Diamond Price Histogram") +
  ggsave('priceHistogram.png') 
```

*** 
```{r, warning=FALSE}
# Break out the histogram of diamond prices by cut.

# You should have five histograms in separate
# panels on your resulting plot.

# TYPE YOUR CODE BELOW THE LINE
# ======================================================
ggplot(data = diamonds, aes(x = price)) + 
  geom_histogram(binwidth = 250, color = 'black', fill = 'light green') + 
  scale_x_continuous(limits = c(250, 5000), breaks = seq(0, 5000, 250)) + 
  labs(x = 'diamond prices in dollars', title = "Diamond Price Histogram") +
  facet_wrap(~cut, ncol = 2)
```

***  
```{r}
print(sort(by(data = diamonds$price, INDICES = diamonds$cut, min)))
print('*************')
print(sort(by(data = diamonds$price, INDICES = diamonds$cut, max)))
print('***********')
print(sort(by(data = diamonds$price, INDICES = diamonds$cut, median)))
```


*** 
```{r}
# Create a histogram of price per carat
# and facet it by cut. You can make adjustments
# to the code from the previous exercise to get
# started.

# Adjust the bin width and transform the scale
# of the x-axis using log10.

# Submit your final code when you are ready.

# ENTER YOUR CODE BELOW THIS LINE.
# ===========================================================================

ggplot(data = diamonds, aes(x = price/carat)) + 
  geom_histogram(bins = 20, color = "dark green", fill = "light blue") + 
  scale_x_log10() + 
  facet_wrap(~cut, ncol = 1) + 
  labs(x = "Price per carats")
  
```

*** 
```{r}
# Investigate the price of diamonds using box plots,
# numerical summaries, and one of the following categorical
# variables: cut, clarity, or color.

# There won’t be a solution video for this
# exercise so go to the discussion thread for either
# BOXPLOTS BY CLARITY, BOXPLOT BY COLOR, or BOXPLOTS BY CUT
# to share you thoughts and to
# see what other people found.

# You can save images by using the ggsave() command.
# ggsave() will save the last plot created.
# For example...
#                  qplot(x = price, data = diamonds)
#                  ggsave('priceHistogram.png')

# ggsave currently recognises the extensions eps/ps, tex (pictex),
# pdf, jpeg, tiff, png, bmp, svg and wmf (windows only).

# Copy and paste all of the code that you used for
# your investigation, and submit it when you are ready.
# =================================================================

ggplot(data = diamonds, aes(y = price, x = clarity)) + 
  geom_boxplot()
```
***
```{r}
summary(diamonds[diamonds$color == "D",]$price)
IQR(diamonds[diamonds$color == "D",]$price)
summary(diamonds[diamonds$color == "J",]$price)
best_color = max(levels(diamonds$color))
best_color
IQR(diamonds[diamonds$color == best_color,]$price)
worst_color = min(levels(diamonds$color))
IQR(diamonds[diamonds$color == worst_color,]$price)
```

Data Wrangling 
https://s3.amazonaws.com/udacity-hosted-downloads/ud651/DataWranglingWithR.pdf 
***
